const stats = [
    {
        name: "Health",
        maxRank: "Platinum III",
        maxMMR:  3509,
        matches: 144,
        wins: 78,
        losses: 65,
        abandons: 1,
        winPercent: 54.17,
    },
    {
        name: "Blood Orchid",
        maxRank: "Platinmu II",
        maxMMR:  3809,
        matches: 106,
        wins: 57,
        losses: 48,
        abandons: 1,
        winPercent: 53.77,
    },
    {
        name: "White Noise",
        maxRank: "Diamond",
        maxMMR:  4726,
        matches: 81,
        wins: 53,
        losses: 28,
        abandons: 0,
        winPercent: 65.43,
    },
    {
        name: "Para Bellum",
        maxRank: "Platinum II",
        maxMMR:  4015,
        matches: 114,
        wins: 66,
        losses: 46,
        abandons: 2,
        winPercent: 57.89,
    },
    {
        name: "Grim Sky",
        maxRank: "Platinum II",
        maxMMR:  3923,
        matches: 65,
        wins: 43,
        losses: 22,
        abandons: 0,
        winPercent: 66.15,
    },
    {
        name: "Wind Bastion",
        maxRank: "Diamond",
        maxMMR:  4508,
        matches: 32,
        wins: 26,
        losses: 6,
        abandons: 0,
        winPercent: 81.25,
    },
    {
        name: "Burnt Horizon",
        maxRank: "Platinum III",
        maxMMR:  3395,
        matches: 44,
        wins: 25,
        losses: 18,
        abandons: 1,
        winPercent: 56.82,
    },
]
module.exports = stats