const stats = [
  {
    id: 1,
    name: "Health",
    maxRank: "Platinum III",
    maxMMR: 3509,
    matches: 144,
    wins: 78,
    losses: 65,
    abandons: 1,
  },
  {
    id: 2,
    name: "Blood Orchid",
    maxRank: "Platinmu II",
    maxMMR: 3809,
    matches: 106,
    wins: 57,
    losses: 48,
    abandons: 1,
  },
  {
    id: 3,
    name: "White Noise",
    maxRank: "Diamond",
    maxMMR: 4726,
    matches: 81,
    wins: 53,
    losses: 28,
    abandons: 0,
  },
  {
    id: 4,
    name: "Para Bellum",
    maxRank: "Platinum II",
    maxMMR: 4015,
    matches: 114,
    wins: 66,
    losses: 46,
    abandons: 2,
  },
  {
    id: 5,
    name: "Grim Sky",
    maxRank: "Platinum II",
    maxMMR: 3923,
    matches: 65,
    wins: 43,
    losses: 22,
    abandons: 0,
  },
  {
    id: 6,
    name: "Wind Bastion",
    maxRank: "Diamond",
    maxMMR: 4508,
    matches: 32,
    wins: 26,
    losses: 6,
    abandons: 0,
  },
  {
    id: 7,
    name: "Burnt Horizon",
    maxRank: "Platinum III",
    maxMMR: 3395,
    matches: 44,
    wins: 25,
    losses: 18,
    abandons: 1,
  },
];
module.exports = stats;
